# Generated by Django 5.0.7 on 2024-08-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAdsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('campaign_name', models.CharField(max_length=255)),
                ('reach', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link_clicks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAdsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('campaign_name', models.CharField(max_length=255)),
                ('clicks', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conversions', models.IntegerField()),
            ],
        ),
    ]
