# Generated by Django 5.0.7 on 2024-08-05 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookadsdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='facebookadsdata',
            name='link_clicks',
        ),
        migrations.RemoveField(
            model_name='facebookadsdata',
            name='reach',
        ),
        migrations.RemoveField(
            model_name='googleadsdata',
            name='campaign_name',
        ),
        migrations.RemoveField(
            model_name='googleadsdata',
            name='conversions',
        ),
        migrations.RemoveField(
            model_name='googleadsdata',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='googleadsdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='googleadsdata',
            name='impressions',
        ),
        migrations.AddField(
            model_name='facebookadsdata',
            name='campaign_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facebookadsdata',
            name='clicks',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='facebookadsdata',
            name='cpc',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='facebookadsdata',
            name='cpm',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='facebookadsdata',
            name='ctr',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='facebookadsdata',
            name='data',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='facebookadsdata',
            name='utm',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='googleadsdata',
            name='campaign_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googleadsdata',
            name='cpc',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='googleadsdata',
            name='ctr',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='googleadsdata',
            name='day',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='googleadsdata',
            name='dominio',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googleadsdata',
            name='total_cost',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='googleadsdata',
            name='utm',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='facebookadsdata',
            name='campaign_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facebookadsdata',
            name='impressions',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='facebookadsdata',
            name='spend',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='googleadsdata',
            name='clicks',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='facebookadsdata',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.facebookaccount'),
        ),
    ]
